### ISSUE TITLE
[20/02/2024] Add JSDoc comments to project

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/JSquarto#24]
Add proper documentation for every section of the project using JSDoc. Later on we should use the same tool to generate the documentation for the project

## TODO
- [x] Add JSDoc comments for project
- [x] Generate documentation using JSQuarto tool
- [x] Host on a github pages
