### ISSUE TITLE
[08/02/2024] Quarto yml file for documentation structure

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/JSquarto#6]
Add a feature to generate the `__quarto.yml` file which will be responsible for outlining the structure of the generated document.
Currently the generated document has no structure, it basically follows the same folder structure as the file in the `/test_files` folder

### TODO
- [x] Generate `quarto.yml` file 
- [x] Account for modules and categories when outlining structure of document in `quarto.yml` file
- [x] Account for chapter categories and subcategories if specified withing the extracted `JSDOC` comments
